# Generated by Django 4.1.2 on 2022-10-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_do', models.CharField(max_length=200)),
                ('done', models.BooleanField()),
                ('created_ap', models.DateField(auto_now_add=True)),
                ('until_date', models.DateField()),
            ],
        ),
    ]
