# Generated by Django 4.1.2 on 2022-10-29 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='created_ap',
            new_name='created_at',
        ),
    ]
